language: java
jdk:
  - openjdk11
addons:
  postgresql: '11.1'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_example' -U postgres
before_install:
  - chmod -R 777 mvnw
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
script:
  - psql -c "SELECT version();"
env:
  global:
    - PGUSER=postgres
    - PGPORT=5432
    - PGPASSWORD=982148
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
notifications:
  webhooks:
    - https://fathomless-fjord-24024.herokuapp.com/notify