language: java
jdk:
  - openjdk11
services:
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
before_script:
  - psql -c 'create database travel_path;' -U postgres
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -q -d travel_path -f src/main/resources/db/travel_path.sql
env:
  global:
    - PGPORT=5433
cache:
  directories:
    - $HOME/.maven/caches
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
notifications:
  webhooks:
    - https://fathomless-fjord-24024.herokuapp.com/notify