server:
  port: 8081
  connection-timeout: 60000
spring:
  datasource:
    druid:
      url: jdbc:postgresql://localhost:5432/travel_path #jdbc:mysql://localhost:3306/travel_path?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: org.postgresql.Driver #com.mysql.cj.jdbc.Driver
      username: postgres
      password: 982148
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 10
      min-idle: 15
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20

mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    xyz.guqing.travelpath: debug