server:
  port: 8080
spring:
  datasource:
    # 使用h2数据库
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.travel-path/db/travelPath
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    initialization-mode: never
    username: root
    password: 123456
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
travel:
  serverUrl: http://localhost:8086
justauth:
  enabled: true
  type:
    github:
      client-id:
      client-secret:
      redirect-uri:
    weibo:
      client-id:
      client-secret:
      redirect-uri:
logging:
  level:
    xyz.guqing.travelpath: INFO
  file:
    path: ${user.home}/.travel-path/logs