server:
  port: 8081
  connection-timeout: 60000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_path?useUnicode=true&characterEncoding=UTF-8&&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 982148

mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    xyz.guqing.travelpath: debug